name: signalr_dart
description: A complete SignalR Client including stateful reconnect in dart. You will feel right at home while using this library
version: 1.0.1
homepage: https://github.com/aeb-dev/signalr_dart
repository: https://github.com/aeb-dev/signalr_dart
issues: https://github.com/aeb-dev/signalr_dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  cancellation_token_dotnet: ^1.0.1
  http: ^1.0.0
  # http2: ^2.2.0
  js: ^0.6.7
  jsontool: ^1.2.0
  logging: ^1.1.1
  meta: ^1.9.1
  msg_pck: ^0.3.0
  os_detect: ^2.0.1
  pool: ^1.5.1
  sse: ^4.1.2
  typed_data: ^1.3.2
  uri: ^1.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  aeb_lint: ^1.1.0
  test: ^1.21.0
